visible_hostname app2-squid

http_port 80 accel defaultsite=web.lab.local no-vhost

cache_peer 192.168.112.11 parent 8080 0 no-query originserver round-robin name=tomcat_app1
cache_peer 192.168.112.12 parent 8080 0 no-query originserver round-robin name=tomcat_app2

acl allowed_clients src 192.168.112.0/24
acl allowed_clients src 127.0.0.1/32

http_access allow allowed_clients
http_access deny all

cache_peer_access tomcat_app1 allow all
cache_peer_access tomcat_app2 allow all

never_direct allow all
cache deny all

access_log stdio:/var/log/squid/access.log
cache_log /var/log/squid/cache.log
