[req]
distinguished_name = dn
x509_extensions = extensions
prompt = no

[dn]
C = LK
O = UCSC
OU = System and Network Administration
CN = web.lab.local

[extensions]
subjectAltName = @alt_names
keyUsage = critical, digitalSignature, keyEncipherment
extendedKeyUsage = serverAuth

[alt_names]
DNS.1 = web.lab.local
IP.1 = 192.168.112.100
