global_defs {
    router_id APP1
    enable_script_security
    script_user root
}

vrrp_script check_squid {
    script "/usr/local/bin/check_squid.sh"
    interval 2
    timeout 2
    fall 2
    rise 2
    weight -30
}

vrrp_instance WEB_VIP {
    state MASTER
    interface ens224
    virtual_router_id 51
    priority 110
    advert_int 1

    authentication {
        auth_type PASS
        auth_pass LabPass1
    }

    unicast_src_ip 192.168.112.11

    unicast_peer {
        192.168.112.12
    }

    virtual_ipaddress {
        192.168.112.100/24 dev ens224
    }

    track_script {
        check_squid
    }
}
